### ISSUE TITLE
stvari za nrdit

### ISSUE THREAD

**Issue by Jamsek-m** [Jamsek-m/vzr-project#1]
procesi: 1, 2, 8, 32, (64)
nodes: 1, (2, 4 MPI)
comm: infiniband, ethernet (MPI)
iteracije: 300
board: 1024, 4096, 8192

----- predstavitev -----
board: 1024, 8192
nodes: 1, 2, 4
comm: oboje
iteracije: 300
procesi: 1, 8, 32

- [ ]  sekvenčni: 1024, 8192
- [ ] openmp: 1, 8, 32 procesov, 1024, 8192
- [ ] MPI rows: 1, 8, 32 procesov, 1024, 8192, infiniband, ethernet, nodes: 1, 2, 4, blocking non-blocking
- [ ] MPI columns:

**Comment by matejbizjak** [comment]
Ratalo use? :D
